# Generated by Django 2.1.7 on 2019-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('real_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_group', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='homework',
        ),
        migrations.DeleteModel(
            name='math',
        ),
        migrations.DeleteModel(
            name='math_test',
        ),
    ]
